"""empty message

Revision ID: 3f0ecdebc6a4
Revises: b91cd33c906d
Create Date: 2017-03-20 17:21:47.685396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0ecdebc6a4'
down_revision = 'b91cd33c906d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'score')
    # ### end Alembic commands ###
